
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
        - name: password-generator
          image: lakshyabandi25/case_study:t2 # use your Docker Hub image
          ports:
            - containerPort: 5000
