apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  selector:
    app: password-generator
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
